{{- if and .Values.secrets.db.ssl.enabled .Values.secrets.db.ssl.caCertPath }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "journai.fullname" . }}-db-ssl-certs
  labels:
    {{- include "journai.labels" . | nindent 4 }}
type: Opaque
data:
  # The certificate will be mounted as rds-ca-cert.pem
  rds-ca-cert.pem: |
    {{- .Files.Get .Values.secrets.db.ssl.caCertPath | b64enc | nindent 4 }}
{{- end }}