apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "journai.fullname" . }}-nginx-conf
  labels:
    {{- include "journai.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
data:
  default.conf: |
    server {
        listen       8080;
        server_name  localhost;
        
        # Security headers
        add_header X-Content-Type-Options nosniff;
        add_header X-Frame-Options "SAMEORIGIN";
        add_header X-XSS-Protection "1; mode=block";
        add_header Referrer-Policy "strict-origin";
        
        # Disable server tokens
        server_tokens off;
        
        # Root directory
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        
        # Enable gzip compression
        gzip on;
        gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;
        
        # API proxy
        location /api/ {
            proxy_pass http://{{ include "journai.fullname" . }}-backend:{{ .Values.backend.service.port }};
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection 'upgrade';
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_cache_bypass $http_upgrade;
            
            # Increase timeouts
            proxy_connect_timeout 300s;
            proxy_send_timeout 300s;
            proxy_read_timeout 300s;
            send_timeout 300s;
        }
        
        # Health check endpoint
        location /health {
            access_log off;
            add_header Content-Type text/plain;
            return 200 'OK';
        }
        
        # Serve static files
        location / {
            try_files $uri $uri/ /index.html;
            
            # Cache control for static assets
            location ~* \.(?:jpg|jpeg|gif|png|ico|cur|gz|svg|svgz|mp4|ogg|ogv|webm|htc|woff2|woff)$ {
                expires 1y;
                access_log off;
                add_header Cache-Control "public";
            }
            
            location ~* \.(?:css|js)$ {
                expires 7d;
                access_log off;
                add_header Cache-Control "public";
            }
        }
        
        # Deny access to . files
        location ~ /\. {
            deny all;
        }
        
        # Error pages
        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   /usr/share/nginx/html;
        }
    }
