apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets-sa
  namespace: {{ .Release.Namespace }}
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::{{ .Values.global.aws.accountId }}:role/journai-eso-role
  labels:
    {{- include "journai.labels" . | nindent 4 }}
